# Bật tính năng chạy song song
junit.jupiter.execution.parallel.enabled = true

# Chế độ chạy song song mặc định (concurrent = chạy đồng thời)
junit.jupiter.execution.parallel.mode.default = concurrent

# Chiến lược phân bổ luồng (dynamic = tự động tính toán dựa trên số nhân CPU)
junit.jupiter.execution.parallel.config.strategy = dynamic
